<a href="https://colab.research.google.com/github/sadighuseyn/DATA1/blob/main/Homework5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Case Intro
Term deposits are a major source of income for a bank. A term deposit is a cash investment held at a financial institution. Your money is invested for an agreed rate of interest over a fixed amount of time, or term. The bank has various outreach plans to sell term deposits to their customers such as email marketing, advertisements, telephonic marketing, and digital marketing.

Telephonic marketing campaigns still remain one of the most effective way to reach out to people. However, they require huge investment as large call centers are hired to actually execute these campaigns. Hence, it is crucial to identify the customers most likely to convert beforehand so that they can be specifically targeted via call.

The data is related to direct marketing campaigns (phone calls) of a Portuguese banking institution. The classification goal is to predict if the client will subscribe to a term deposit (variable y).

Content
The data is related to the direct marketing campaigns of a Portuguese banking institution. The marketing campaigns were based on phone calls. Often, more than one contact to the same client was required, in order to access if the product (bank term deposit) would be ('yes') or not ('no') subscribed by the customer or not. The data folder contains two datasets:-

Bank.csv: 45,211 rows and 18 columns ordered by date (from May 2008 to November 2010)

Detailed Column Descriptions
bank client data:

1 - age (numeric)

2 - job : type of job (categorical: "admin.","unknown","unemployed","management","housemaid","entrepreneur","student",
"blue-collar","self-employed","retired","technician","services")

3 - marital : marital status (categorical: "married","divorced","single"; note: "divorced" means divorced or widowed)

4 - education (categorical: "unknown","secondary","primary","tertiary")

5 - default: has credit in default? (binary: "yes","no")

6 - balance: average yearly balance, in euros (numeric)

7 - housing: has housing loan? (binary: "yes","no")

8 - loan: has personal loan? (binary: "yes","no")
# related with the last contact of the current campaign:
9 - contact: contact communication type (categorical: "unknown","telephone","cellular")
10 - day: last contact day of the month (numeric)

11 - month: last contact month of year (categorical: "jan", "feb", "mar", â€¦, "nov", "dec")

12 - duration: last contact duration, in seconds (numeric)

# other attributes:
13 - campaign: number of contacts performed during this campaign and for this client (numeric, includes last contact)

14 - pdays: number of days that passed by after the client was last contacted from a previous campaign (numeric, -1 means client was not previously contacted)

15 - previous: number of contacts performed before this campaign and for this client (numeric)

16 - poutcome: outcome of the previous marketing campaign (categorical: "unknown","other","failure","success")

Output variable (desired target):

17 - y - has the client subscribed a term deposit? (binary: "yes","no")

Missing Attribute Values: None

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv('https://raw.githubusercontent.com/ogut77/DataScience/main/data/Bank.csv',sep = ';')
df

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,no,cellular,17,nov,977,3,-1,0,unknown,yes
45207,71,retired,divorced,primary,no,1729,no,no,cellular,17,nov,456,2,-1,0,unknown,yes
45208,72,retired,married,secondary,no,5715,no,no,cellular,17,nov,1127,5,184,3,success,yes
45209,57,blue-collar,married,secondary,no,668,no,no,telephone,17,nov,508,4,-1,0,unknown,no
45210,37,entrepreneur,married,secondary,no,2971,no,no,cellular,17,nov,361,2,188,11,other,no

In [2]:
print(df.shape)
df.info()
df.isnull().sum()

(45211, 17)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64
 12  campaign   45211 non-null  int64
 13  pdays      45211 non-null  int64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  object
 16  y          45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [3]:
#For object check the data 
for cn in df.columns:
  if(df[cn].dtype==object):
    print(df[cn].value_counts())

blue-collar      9732
management       9458
technician       7597
admin.           5171
services         4154
retired          2264
self-employed    1579
entrepreneur     1487
unemployed       1303
housemaid        1240
student           938
unknown           288
Name: job, dtype: int64
married     27214
single      12790
divorced     5207
Name: marital, dtype: int64
secondary    23202
tertiary     13301
primary       6851
unknown       1857
Name: education, dtype: int64
no     44396
yes      815
Name: default, dtype: int64
yes    25130
no     20081
Name: housing, dtype: int64
no     37967
yes     7244
Name: loan, dtype: int64
cellular     29285
unknown      13020
telephone     2906
Name: contact, dtype: int64
may    13766
jul     6895
aug     6247
jun     5341
nov     3970
apr     2932
feb     2649
jan     1403
oct      738
sep      579
mar      477
dec      214
Name: month, dtype: int64
unknown    36959
failure     4901
other       1840
success     1511
Name: poutcome, dtype: int64
no     39922
yes     5289
Name: y, dtype: int64

In [4]:
def Encoder(df):
          from sklearn import preprocessing
          columnsToEncode = list(df.select_dtypes(include=['category','object']))
          le = preprocessing.LabelEncoder()
          for feature in columnsToEncode:
              try:
                  df[feature] = le.fit_transform(df[feature])
              except:
                  print('Error encoding '+feature)
          return df

In [5]:
df=Encoder(df)
df

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,4,1,2,0,2143,1,0,2,5,8,261,1,-1,0,3,0
1,44,9,2,1,0,29,1,0,2,5,8,151,1,-1,0,3,0
2,33,2,1,1,0,2,1,1,2,5,8,76,1,-1,0,3,0
3,47,1,1,3,0,1506,1,0,2,5,8,92,1,-1,0,3,0
4,33,11,2,3,0,1,0,0,2,5,8,198,1,-1,0,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,9,1,2,0,825,0,0,0,17,9,977,3,-1,0,3,1
45207,71,5,0,0,0,1729,0,0,0,17,9,456,2,-1,0,3,1
45208,72,5,1,1,0,5715,0,0,0,17,9,1127,5,184,3,2,1
45209,57,1,1,1,0,668,0,0,1,17,9,508,4,-1,0,3,0
45210,37,2,1,1,0,2971,0,0,0,17,9,361,2,188,11,1,0

In [6]:
y = df['y'] #Output
X = df.drop('y',axis=1)
X

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome
0,58,4,1,2,0,2143,1,0,2,5,8,261,1,-1,0,3
1,44,9,2,1,0,29,1,0,2,5,8,151,1,-1,0,3
2,33,2,1,1,0,2,1,1,2,5,8,76,1,-1,0,3
3,47,1,1,3,0,1506,1,0,2,5,8,92,1,-1,0,3
4,33,11,2,3,0,1,0,0,2,5,8,198,1,-1,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,9,1,2,0,825,0,0,0,17,9,977,3,-1,0,3
45207,71,5,0,0,0,1729,0,0,0,17,9,456,2,-1,0,3
45208,72,5,1,1,0,5715,0,0,0,17,9,1127,5,184,3,2
45209,57,1,1,1,0,668,0,0,1,17,9,508,4,-1,0,3
45210,37,2,1,1,0,2971,0,0,0,17,9,361,2,188,11,1

In [7]:
from sklearn.model_selection import  train_test_split


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=17)

 


Q1)Using  Random Forest,XGBoost, Light GBM and Gradient Boosting Classifier with default parameters (no parameter specifications except random_state) calculate Accuracy on Test data. Which method gives the best accuracy on test data

In [17]:
from scipy.sparse.construct import rand
#RAndom Forest:
from sklearn.metrics import accuracy_score

from sklearn.ensemble import RandomForestClassifier
forest=RandomForestClassifier(random_state=17)
forest.fit(X_train, y_train)

forest_pred= forest.predict (X_test)
print(accuracy_score(y_test, forest_pred))

# XGBoost:
from xgboost import XGBClassifier
model= XGBClassifier(random_state=17)
model.fit(X_train, y_train)

model_pred=model.predict(X_test)
print(accuracy_score(y_test, xgb_pred))

#Light GBM:
import lightgbm as lgb
lgb_model= lgb. LGBMClassifier(random_state=17)
lgb_model.fit(X_train, y_train)
print(accuracy_score(y_test, lgb_model.predict(X_test)))

#Gradient Boosting Classifier:
from sklearn.ensemble import GradientBoostingClassifier
gbm_model= GradientBoostingClassifier(random_state=17)
gbm_model.fit(X_train, y_train)
print(accuracy_score(y_test, gbm_model.predict(X_test)))

0.9025037600636999
0.90020348580023
0.9044501459789437
0.9018844554543042

Q2) Using optuna hyperparmeter optimization technique and 100 trial

 a)find best methods with  parameters  using Cross validation (CV=3) technique for the range of   parameters below. What are the best parameters for the method with highest cross validation accuracy?

"max_depth": range(2, 16), "max_features": range(2, 16)

 b)Evaluate the performance of the  method with highest cross validation accuracy on test data.What is the accuracy value?

In [ ]:
!pip install optuna

In [21]:
import optuna

import sklearn.datasets
import sklearn.ensemble
import sklearn.model_selection
import sklearn.svm

def objective(trial):
  x, y = X_test, y_test

  classifier_name= trial.suggest_categorical("classifier", ["Random Forest", "XGBoost", "LightGBM", "GradientBoostingClassifier"])
  if classifier_name== "Random Forest":
       from sklearn.ensemble import RandomForestClassifier
       max_depth= trial.suggest_int("max_depth", 2, X_test.shape[1])
       max_features= trial.suggest_int("max_features", 2, X_test.shape[1])
       classifier_obj=sklearn.ensemble.RandomForestClassifier(random_state=17, max_depth= max_depth, max_features= max_features)

  elif classifier_name=="XGBoost":
       from xgboost import XGBClassifier
       max_depth= trial.suggest_int("max_depth", 2, X_test.shape[1])
       max_features= trial.suggest_int("max_features", 2, X_test.shape[1])
       classifier_obj=XGBClassifier(random_state=17, max_depth= max_depth, max_features= max_features)

  elif classifier_name== "LightGBM":
       import lightgbm as lgb
       max_depth= trial.suggest_int("max_depth", 2, X_test.shape[1])
       max_features= trial.suggest_int("max_features", 2, X_test.shape[1])
       classifier_obj=lgb.LGBMClassifier(random_state=17, max_depth= max_depth, max_features= max_features)
    
  else:
       max_depth= trial.suggest_int("max_depth", 2, X_test.shape[1])
       max_features= trial.suggest_int("max_features", 2, X_test.shape[1])
       classifier_obj=sklearn.ensemble.GradientBoostingClassifier(random_state=17, max_depth= max_depth, max_features= max_features)

  accuracy=sklearn.model_selection.cross_val_score(classifier_obj, x, y, n_jobs=-1, cv=3).mean()

  return accuracy

if __name__== "__main__":
    study = optuna.create_study(direction="maximize")
    study.optimize(objective, n_trials=100)
    print(study.best_trial)

[I 2022-03-27 19:06:45,203] A new study created in memory with name: no-name-67ffdcac-800a-45a1-8829-310f459214c2
[I 2022-03-27 19:06:46,468] Trial 0 finished with value: 0.9022387728121312 and parameters: {'classifier': 'LightGBM', 'max_depth': 8, 'max_features': 10}. Best is trial 0 with value: 0.9022387728121312.
[I 2022-03-27 19:07:09,555] Trial 1 finished with value: 0.8969301891815372 and parameters: {'classifier': 'GradientBoostingClassifier', 'max_depth': 15, 'max_features': 6}. Best is trial 0 with value: 0.9022387728121312.
[I 2022-03-27 19:07:10,318] Trial 2 finished with value: 0.9013538718836486 and parameters: {'classifier': 'LightGBM', 'max_depth': 16, 'max_features': 15}. Best is trial 0 with value: 0.9022387728121312.
[I 2022-03-27 19:07:12,286] Trial 3 finished with value: 0.8971953236387589 and parameters: {'classifier': 'Random Forest', 'max_depth': 4, 'max_features': 9}. Best is trial 0 with value: 0.9022387728121312.
[I 2022-03-27 19:07:13,045] Trial 4 finished with value: 0.9013538718836486 and parameters: {'classifier': 'LightGBM', 'max_depth': 16, 'max_features': 15}. Best is trial 0 with value: 0.9022387728121312.
[I 2022-03-27 19:07:17,561] Trial 5 finished with value: 0.8997614212597161 and parameters: {'classifier': 'Random Forest', 'max_depth': 13, 'max_features': 10}. Best is trial 0 with value: 0.9022387728121312.
[I 2022-03-27 19:07:23,387] Trial 6 finished with value: 0.898788103038812 and parameters: {'classifier': 'Random Forest', 'max_depth': 12, 'max_features': 14}. Best is trial 0 with value: 0.9022387728121312.
[I 2022-03-27 19:07:30,177] Trial 7 finished with value: 0.8967532371766511 and parameters: {'classifier': 'XGBoost', 'max_depth': 15, 'max_features': 11}. Best is trial 0 with value: 0.9022387728121312.
[I 2022-03-27 19:07:32,968] Trial 8 finished with value: 0.8996730744193204 and parameters: {'classifier': 'Random Forest', 'max_depth': 5, 'max_features': 12}. Best is trial 0 with value: 0.9022387728121312.
[I 2022-03-27 19:07:33,705] Trial 9 finished with value: 0.9022387728121312 and parameters: {'classifier': 'LightGBM', 'max_depth': 8, 'max_features': 12}. Best is trial 0 with value: 0.9022387728121312.
[I 2022-03-27 19:07:37,432] Trial 10 finished with value: 0.900822898448947 and parameters: {'classifier': 'XGBoost', 'max_depth': 8, 'max_features': 3}. Best is trial 0 with value: 0.9022387728121312.
[I 2022-03-27 19:07:38,190] Trial 11 finished with value: 0.9022387728121312 and parameters: {'classifier': 'LightGBM', 'max_depth': 8, 'max_features': 7}. Best is trial 0 with value: 0.9022387728121312.
[I 2022-03-27 19:07:38,952] Trial 12 finished with value: 0.9020615624831502 and parameters: {'classifier': 'LightGBM', 'max_depth': 10, 'max_features': 13}. Best is trial 0 with value: 0.9022387728121312.
[I 2022-03-27 19:07:39,672] Trial 13 finished with value: 0.902061820807245 and parameters: {'classifier': 'LightGBM', 'max_depth': 6, 'max_features': 8}. Best is trial 0 with value: 0.9022387728121312.
[I 2022-03-27 19:07:40,565] Trial 14 finished with value: 0.8989649141396465 and parameters: {'classifier': 'GradientBoostingClassifier', 'max_depth': 2, 'max_features': 3}. Best is trial 0 with value: 0.9022387728121312.
[I 2022-03-27 19:07:41,342] Trial 15 finished with value: 0.9020615624831502 and parameters: {'classifier': 'LightGBM', 'max_depth': 10, 'max_features': 11}. Best is trial 0 with value: 0.9022387728121312.
[I 2022-03-27 19:07:42,053] Trial 16 finished with value: 0.9007344341885082 and parameters: {'classifier': 'LightGBM', 'max_depth': 7, 'max_features': 5}. Best is trial 0 with value: 0.9022387728121312.
[I 2022-03-27 19:07:42,798] Trial 17 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 7}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:07:54,741] Trial 18 finished with value: 0.9017961227338166 and parameters: {'classifier': 'GradientBoostingClassifier', 'max_depth': 12, 'max_features': 7}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:07:59,497] Trial 19 finished with value: 0.8997613742916988 and parameters: {'classifier': 'XGBoost', 'max_depth': 10, 'max_features': 5}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:08:00,278] Trial 20 finished with value: 0.9020614450631071 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 9}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:08:01,031] Trial 21 finished with value: 0.9025041186254302 and parameters: {'classifier': 'LightGBM', 'max_depth': 9, 'max_features': 7}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:08:01,796] Trial 22 finished with value: 0.9025041186254302 and parameters: {'classifier': 'LightGBM', 'max_depth': 9, 'max_features': 7}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:08:02,570] Trial 23 finished with value: 0.9020615624831502 and parameters: {'classifier': 'LightGBM', 'max_depth': 10, 'max_features': 5}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:08:03,355] Trial 24 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 2}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:08:04,120] Trial 25 finished with value: 0.9009117149695149 and parameters: {'classifier': 'LightGBM', 'max_depth': 13, 'max_features': 2}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:08:04,890] Trial 26 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 4}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:08:10,222] Trial 27 finished with value: 0.8986996387783731 and parameters: {'classifier': 'XGBoost', 'max_depth': 11, 'max_features': 2}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:08:27,603] Trial 28 finished with value: 0.8979918542428371 and parameters: {'classifier': 'GradientBoostingClassifier', 'max_depth': 14, 'max_features': 4}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:08:28,346] Trial 29 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 4}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:08:29,624] Trial 30 finished with value: 0.9009117149695149 and parameters: {'classifier': 'LightGBM', 'max_depth': 13, 'max_features': 3}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:08:30,396] Trial 31 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 4}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:08:31,179] Trial 32 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 4}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:08:31,922] Trial 33 finished with value: 0.9030348102520286 and parameters: {'classifier': 'LightGBM', 'max_depth': 14, 'max_features': 4}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:08:32,672] Trial 34 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 2}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:08:33,453] Trial 35 finished with value: 0.9020614450631071 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 6}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:08:39,103] Trial 36 finished with value: 0.9002036251418669 and parameters: {'classifier': 'GradientBoostingClassifier', 'max_depth': 9, 'max_features': 6}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:08:41,201] Trial 37 finished with value: 0.8984339641889535 and parameters: {'classifier': 'Random Forest', 'max_depth': 14, 'max_features': 3}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:08:41,963] Trial 38 finished with value: 0.9009117149695149 and parameters: {'classifier': 'LightGBM', 'max_depth': 13, 'max_features': 4}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:08:43,851] Trial 39 finished with value: 0.8957799189557468 and parameters: {'classifier': 'Random Forest', 'max_depth': 15, 'max_features': 2}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:08:44,577] Trial 40 finished with value: 0.9007344341885082 and parameters: {'classifier': 'LightGBM', 'max_depth': 7, 'max_features': 8}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:08:45,355] Trial 41 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 5}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:08:46,129] Trial 42 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 5}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:08:46,876] Trial 43 finished with value: 0.9020614450631071 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 3}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:08:51,666] Trial 44 finished with value: 0.8997613742916988 and parameters: {'classifier': 'XGBoost', 'max_depth': 10, 'max_features': 4}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:08:52,463] Trial 45 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 5}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:08:53,223] Trial 46 finished with value: 0.9009117149695149 and parameters: {'classifier': 'LightGBM', 'max_depth': 13, 'max_features': 16}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:08:56,351] Trial 47 finished with value: 0.9007345985765683 and parameters: {'classifier': 'Random Forest', 'max_depth': 12, 'max_features': 6}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:08:57,092] Trial 48 finished with value: 0.9025041186254302 and parameters: {'classifier': 'LightGBM', 'max_depth': 9, 'max_features': 4}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:08:57,872] Trial 49 finished with value: 0.9020615624831502 and parameters: {'classifier': 'LightGBM', 'max_depth': 10, 'max_features': 2}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:09:01,984] Trial 50 finished with value: 0.9000267905570238 and parameters: {'classifier': 'GradientBoostingClassifier', 'max_depth': 8, 'max_features': 5}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:09:02,751] Trial 51 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 3}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:09:03,502] Trial 52 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 5}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:09:04,244] Trial 53 finished with value: 0.9020615624831502 and parameters: {'classifier': 'LightGBM', 'max_depth': 10, 'max_features': 6}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:09:05,009] Trial 54 finished with value: 0.9020614450631071 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 3}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:09:05,765] Trial 55 finished with value: 0.9020614450631071 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 3}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:09:11,063] Trial 56 finished with value: 0.8986996387783731 and parameters: {'classifier': 'XGBoost', 'max_depth': 11, 'max_features': 5}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:09:11,488] Trial 57 finished with value: 0.8988765907832593 and parameters: {'classifier': 'LightGBM', 'max_depth': 2, 'max_features': 2}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:09:12,250] Trial 58 finished with value: 0.9025041186254302 and parameters: {'classifier': 'LightGBM', 'max_depth': 9, 'max_features': 8}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:09:13,028] Trial 59 finished with value: 0.9020615624831502 and parameters: {'classifier': 'LightGBM', 'max_depth': 10, 'max_features': 5}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:09:15,658] Trial 60 finished with value: 0.901795981829765 and parameters: {'classifier': 'Random Forest', 'max_depth': 16, 'max_features': 4}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:09:16,416] Trial 61 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 7}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:09:17,176] Trial 62 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 4}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:09:17,922] Trial 63 finished with value: 0.9020615624831502 and parameters: {'classifier': 'LightGBM', 'max_depth': 10, 'max_features': 10}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:09:18,669] Trial 64 finished with value: 0.9009117149695149 and parameters: {'classifier': 'LightGBM', 'max_depth': 13, 'max_features': 4}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:09:19,362] Trial 65 finished with value: 0.9020614450631071 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 2}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:09:24,027] Trial 66 finished with value: 0.8988767082033023 and parameters: {'classifier': 'GradientBoostingClassifier', 'max_depth': 9, 'max_features': 3}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:09:24,812] Trial 67 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 7}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:09:25,575] Trial 68 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 8}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:09:30,388] Trial 69 finished with value: 0.8997613742916988 and parameters: {'classifier': 'XGBoost', 'max_depth': 10, 'max_features': 6}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:09:31,151] Trial 70 finished with value: 0.9030348102520286 and parameters: {'classifier': 'LightGBM', 'max_depth': 14, 'max_features': 2}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:09:31,895] Trial 71 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 8}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:09:32,649] Trial 72 finished with value: 0.9020614450631071 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 9}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:09:33,422] Trial 73 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 10}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:09:34,195] Trial 74 finished with value: 0.9020615624831502 and parameters: {'classifier': 'LightGBM', 'max_depth': 10, 'max_features': 12}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:09:34,972] Trial 75 finished with value: 0.9009117149695149 and parameters: {'classifier': 'LightGBM', 'max_depth': 13, 'max_features': 10}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:09:35,763] Trial 76 finished with value: 0.9020614450631071 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 4}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:09:36,547] Trial 77 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 5}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:09:37,019] Trial 78 finished with value: 0.9025927237899207 and parameters: {'classifier': 'LightGBM', 'max_depth': 3, 'max_features': 6}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:09:39,238] Trial 79 finished with value: 0.9007344107044997 and parameters: {'classifier': 'Random Forest', 'max_depth': 8, 'max_features': 5}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:09:47,189] Trial 80 finished with value: 0.8978151135940284 and parameters: {'classifier': 'GradientBoostingClassifier', 'max_depth': 10, 'max_features': 8}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:09:47,948] Trial 81 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 9}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:09:48,701] Trial 82 finished with value: 0.9020614450631071 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 11}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:09:49,450] Trial 83 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 6}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:09:50,232] Trial 84 finished with value: 0.9020614450631071 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 3}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:09:51,006] Trial 85 finished with value: 0.9025041186254302 and parameters: {'classifier': 'LightGBM', 'max_depth': 9, 'max_features': 6}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:09:51,750] Trial 86 finished with value: 0.9020615624831502 and parameters: {'classifier': 'LightGBM', 'max_depth': 10, 'max_features': 3}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:09:57,091] Trial 87 finished with value: 0.8986996387783731 and parameters: {'classifier': 'XGBoost', 'max_depth': 11, 'max_features': 7}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:09:57,840] Trial 88 finished with value: 0.9009117149695149 and parameters: {'classifier': 'LightGBM', 'max_depth': 13, 'max_features': 9}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:09:58,589] Trial 89 finished with value: 0.9007344341885082 and parameters: {'classifier': 'LightGBM', 'max_depth': 7, 'max_features': 8}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:09:59,373] Trial 90 finished with value: 0.9020614450631071 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 10}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:10:00,150] Trial 91 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 2}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:10:00,904] Trial 92 finished with value: 0.9020615624831502 and parameters: {'classifier': 'LightGBM', 'max_depth': 10, 'max_features': 5}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:10:01,685] Trial 93 finished with value: 0.9041851744138532 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 4}. Best is trial 17 with value: 0.9041851744138532.
[I 2022-03-27 19:10:02,471] Trial 94 finished with value: 0.9020615624831502 and parameters: {'classifier': 'LightGBM', 'max_depth': 10, 'max_features': 3}. Best is trial 17 with value: 0.9041851744138532.

FrozenTrial(number=17, values=[0.9041851744138532], datetime_start=datetime.datetime(2022, 3, 27, 19, 7, 42, 57376), datetime_complete=datetime.datetime(2022, 3, 27, 19, 7, 42, 798126), params={'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 7}, distributions={'classifier': CategoricalDistribution(choices=('Random Forest', 'XGBoost', 'LightGBM', 'GradientBoostingClassifier')), 'max_depth': IntUniformDistribution(high=16, low=2, step=1), 'max_features': IntUniformDistribution(high=16, low=2, step=1)}, user_attrs={}, system_attrs={}, intermediate_values={}, trial_id=17, state=TrialState.COMPLETE, value=None)

For Q3 and Q4 ,use the following data.

In [22]:
dr=pd.read_csv('https://raw.githubusercontent.com/ogut77/DataScience/main/data/diamond.csv')
dr

,Carat Weight,Cut,Color,Clarity,Polish,Symmetry,Report,Price
0,1.10,Ideal,H,SI1,VG,EX,GIA,5169
1,0.83,Ideal,H,VS1,ID,ID,AGSL,3470
2,0.85,Ideal,H,SI1,EX,EX,GIA,3183
3,0.91,Ideal,E,SI1,VG,VG,GIA,4370
4,0.83,Ideal,G,SI1,EX,EX,GIA,3171
...,...,...,...,...,...,...,...,...
5995,1.03,Ideal,D,SI1,EX,EX,GIA,6250
5996,1.00,Very Good,D,SI1,VG,VG,GIA,5328
5997,1.02,Ideal,D,SI1,EX,EX,GIA,6157
5998,1.27,Signature-Ideal,G,VS1,EX,EX,GIA,11206
5999,2.19,Ideal,E,VS1,EX,EX,GIA,30507

In [23]:
def Encoder(df):
          from sklearn import preprocessing
          columnsToEncode = list(df.select_dtypes(include=['category','object']))
          le = preprocessing.LabelEncoder()
          for feature in columnsToEncode:
              try:
                  df[feature] = le.fit_transform(df[feature])
              except:
                  print('Error encoding '+feature)
          return df

In [24]:
dr=Encoder(dr)
dr

      Carat Weight  Cut  Color  Clarity  Polish  Symmetry  Report  Price
0             1.10    2      4        2       3         0       1   5169
1             0.83    2      4        3       2         2       0   3470
2             0.85    2      4        2       0         0       1   3183
3             0.91    2      1        2       3         3       1   4370
4             0.83    2      3        2       0         0       1   3171
...            ...  ...    ...      ...     ...       ...     ...    ...
5995          1.03    2      0        2       0         0       1   6250
5996          1.00    4      0        2       3         3       1   5328
5997          1.02    2      0        2       0         0       1   6157
5998          1.27    3      3        3       0         0       1  11206
5999          2.19    2      1        3       0         0       1  30507

[6000 rows x 8 columns]

In [25]:
y = dr['Price'] #Output
X = dr.drop('Price',axis=1)
X

      Carat Weight  Cut  Color  Clarity  Polish  Symmetry  Report
0             1.10    2      4        2       3         0       1
1             0.83    2      4        3       2         2       0
2             0.85    2      4        2       0         0       1
3             0.91    2      1        2       3         3       1
4             0.83    2      3        2       0         0       1
...            ...  ...    ...      ...     ...       ...     ...
5995          1.03    2      0        2       0         0       1
5996          1.00    4      0        2       3         3       1
5997          1.02    2      0        2       0         0       1
5998          1.27    3      3        3       0         0       1
5999          2.19    2      1        3       0         0       1

[6000 rows x 7 columns]

In [26]:
from sklearn.model_selection import  train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=17)

Q3)Using Linear Regression,Decison Tree Random Forest,XGBoost, Light GBM and Gradient Boosting Classifier with default parameters (no parameter specifications except random_state) calculate R2 statistics on test data. Which method gives the best accuracy on test data

In [44]:
from pandas.core.common import random_state
def evalmetric(y,ypred):
 import numpy as np
 e = y - ypred 
 mse_f = np.mean(e**2)
 rmse_f = np.sqrt(mse_f)
 mae_f = np.mean(abs(e))
 mape_f = 100*np.mean(abs(e/y))
 r2_f = 1-(sum(e**2)/sum((y-np.mean(y))**2))
 print("MSE:", mse_f)
 print("RMSE:", rmse_f)
 print("MAE:",mae_f)
 print("MAPE:",mape_f)
 print("R-Squared:", r2_f)

#Linear Regression
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X_train, y_train)

print('Linear Regression')
pred=reg.predict(X_test)
evalmetric(y_test,pred)
print( )

#Decision Tree
from sklearn.tree import DecisionTreeRegressor
dtr = DecisionTreeRegressor(random_state=17)
dtr.fit(X_train,y_train)

print('Decision Tree')
y_pred2 = dtr.predict(X_test)
evalmetric(y_test,y_pred2)
print( )

#Random Forest
from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor(random_state=17)
rfr.fit(X_train,y_train)

print('Random Forest')
y_pred2 = rfr.predict(X_test)
evalmetric(y_test,y_pred2)
print( )

#XGBoost
from xgboost import XGBRegressor
xgr = XGBRegressor(random_state=17)
xgr.fit(X_train, y_train)

print('TXGBoost')
y_pred2 = xgr.predict(X_test)
evalmetric(y_test,y_pred2)
print( )

#Light GBM
from time import time
import lightgbm as lgb
t0 = time()
lgr = lgb.LGBMRegressor(random_state=17)
lgr.fit(X_train, y_train)

print('Light GBM')
y_pred2 = lgr.predict(X_test)
evalmetric(y_test,y_pred2)
print( )

#Gradient Boosting
from sklearn.ensemble import GradientBoostingRegressor
from time import time

gbr = GradientBoostingRegressor(random_state=17)
gbr.fit(X_train, y_train)

print('Gradient Boosting')
y_pred2 = gbr.predict(X_test)
evalmetric(y_test,y_pred2)

Linear Regression
MSE: 18292450.049325157
RMSE: 4276.967389322153
MAE: 2701.997276609754
MAPE: 30.68442425409791
R-Squared: 0.8233845829696962

Decision Tree
MSE: 4222331.073863685
RMSE: 2054.83115458757
MAE: 1016.694373015873
MAPE: 7.833274374700561
R-Squared: 0.9592329752745201

Random Forest
MSE: 2074962.900565573
RMSE: 1440.4731516295515
MAE: 778.3143303628775
MAPE: 6.220426902140035
R-Squared: 0.9799660276771226

[19:51:38] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
TXGBoost
MSE: 2822838.991584785
RMSE: 1680.1306471774108
MAE: 881.3905965169271
MAPE: 7.3386749783130245
R-Squared: 0.9727452099437854

Light GBM
MSE: 1940840.8294753155
RMSE: 1393.1406352107153
MAE: 701.0864858904304
MAPE: 5.433753614630323
R-Squared: 0.9812609895578275

Gradient Boosting
MSE: 2702865.535065862
RMSE: 1644.0393958375396
MAE: 878.4993508475277
MAPE: 7.394144503096002
R-Squared: 0.9739035655494326

Q4) Using optuna hyperparmeter optimization technique (100 trial)  with Random Forest,XGBoost, Light GBM and Gradient Boosting Regressor

a)find best methods with  parameters  using Cross validation (CV=3) technique for the range of   parameters below. What are the best parameters for the method with highest cross validation R2?

"max_depth": range(2, 7), "max_features": range(2, 7)

 b)Evaluate the performance of the  method with highest cross validation R2 on test data. What is the R2 value?

In [ ]:
!pip install optuna

In [45]:
import optuna

import sklearn.datasets
import sklearn.ensemble
import sklearn.model_selection
import sklearn.svm

def objective(trial):
    x, y = X_train,y_train

    regressor_name = trial.suggest_categorical("regressor", ["GradientBoosting", "XGBoost","LightGBM","RandomForest"])
    if regressor_name == "GradientBoosting":
         max_depth = trial.suggest_int("max_depth", 2,7)
         max_features = trial.suggest_int("max_features", 2,7)
         regressor_obj = sklearn.ensemble.GradientBoostingRegressor(random_state=17,  max_depth=max_depth, max_features=max_features )
    
    elif regressor_name == "XGBoost":
         from xgboost import XGBRegressor
         max_depth = trial.suggest_int("max_depth", 2,7)
         max_features = trial.suggest_int("max_features", 2,7)
         regressor_obj = XGBRegressor(random_state=17,  max_depth=max_depth, max_features=max_features )
        
         

    elif regressor_name == "LightGBM":
         import lightgbm as lgb
         max_depth = trial.suggest_int("max_depth", 2,7)
         max_features = trial.suggest_int("max_features", 2,7)
         regressor_obj = lgb.LGBMRegressor(random_state=17,  max_depth=max_depth, max_features=max_features )
        
       
   
    else:
         max_depth = trial.suggest_int("max_depth", 2,7)
         max_features = trial.suggest_int("max_features", 2,7)
         regressor_obj = sklearn.ensemble.RandomForestRegressor(random_state=17,  max_depth=max_depth, max_features=max_features )

     

    r2=sklearn.model_selection.cross_val_score(regressor_obj, x, y, n_jobs=-1, cv=3).mean()
   
    return r2


if __name__ == "__main__":
    study = optuna.create_study(direction="maximize")
    study.optimize(objective, n_trials=100)
    print(study.best_trial)

[I 2022-03-27 19:52:10,174] A new study created in memory with name: no-name-ee9fb611-9d5e-4437-a00d-856b0492510d
[I 2022-03-27 19:52:10,927] Trial 0 finished with value: 0.9840024346566438 and parameters: {'regressor': 'XGBoost', 'max_depth': 7, 'max_features': 6}. Best is trial 0 with value: 0.9840024346566438.
[I 2022-03-27 19:52:11,635] Trial 1 finished with value: 0.9533571582401862 and parameters: {'regressor': 'RandomForest', 'max_depth': 7, 'max_features': 3}. Best is trial 0 with value: 0.9840024346566438.
[I 2022-03-27 19:52:12,267] Trial 2 finished with value: 0.9375844290578602 and parameters: {'regressor': 'RandomForest', 'max_depth': 6, 'max_features': 3}. Best is trial 0 with value: 0.9840024346566438.
[I 2022-03-27 19:52:12,484] Trial 3 finished with value: 0.9758941121368242 and parameters: {'regressor': 'LightGBM', 'max_depth': 6, 'max_features': 7}. Best is trial 0 with value: 0.9840024346566438.
[I 2022-03-27 19:52:13,029] Trial 4 finished with value: 0.8437742151001094 and parameters: {'regressor': 'RandomForest', 'max_depth': 5, 'max_features': 2}. Best is trial 0 with value: 0.9840024346566438.
[I 2022-03-27 19:52:13,706] Trial 5 finished with value: 0.9845567951821383 and parameters: {'regressor': 'XGBoost', 'max_depth': 6, 'max_features': 7}. Best is trial 5 with value: 0.9845567951821383.
[I 2022-03-27 19:52:14,168] Trial 6 finished with value: 0.9837177913038949 and parameters: {'regressor': 'XGBoost', 'max_depth': 4, 'max_features': 4}. Best is trial 5 with value: 0.9845567951821383.
[I 2022-03-27 19:52:14,924] Trial 7 finished with value: 0.9856357090076635 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 7}. Best is trial 7 with value: 0.9856357090076635.
[I 2022-03-27 19:52:15,406] Trial 8 finished with value: 0.9842471016293839 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 3}. Best is trial 7 with value: 0.9856357090076635.
[I 2022-03-27 19:52:16,299] Trial 9 finished with value: 0.9720558623263608 and parameters: {'regressor': 'RandomForest', 'max_depth': 7, 'max_features': 6}. Best is trial 7 with value: 0.9856357090076635.
[I 2022-03-27 19:52:16,642] Trial 10 finished with value: 0.9560583850918647 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 2, 'max_features': 5}. Best is trial 7 with value: 0.9856357090076635.
[I 2022-03-27 19:52:17,258] Trial 11 finished with value: 0.985430200504429 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 4, 'max_features': 7}. Best is trial 7 with value: 0.9856357090076635.
[I 2022-03-27 19:52:17,714] Trial 12 finished with value: 0.9783683994728235 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 3, 'max_features': 6}. Best is trial 7 with value: 0.9856357090076635.
[I 2022-03-27 19:52:18,326] Trial 13 finished with value: 0.985430200504429 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 4, 'max_features': 7}. Best is trial 7 with value: 0.9856357090076635.
[I 2022-03-27 19:52:18,758] Trial 14 finished with value: 0.978584587565372 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 3, 'max_features': 5}. Best is trial 7 with value: 0.9856357090076635.
[I 2022-03-27 19:52:18,921] Trial 15 finished with value: 0.9761140473772666 and parameters: {'regressor': 'LightGBM', 'max_depth': 4, 'max_features': 7}. Best is trial 7 with value: 0.9856357090076635.
[I 2022-03-27 19:52:19,391] Trial 16 finished with value: 0.9783683994728235 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 3, 'max_features': 6}. Best is trial 7 with value: 0.9856357090076635.
[I 2022-03-27 19:52:19,992] Trial 17 finished with value: 0.9851666718949561 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 5}. Best is trial 7 with value: 0.9856357090076635.
[I 2022-03-27 19:52:20,384] Trial 18 finished with value: 0.9568202060524347 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 2, 'max_features': 7}. Best is trial 7 with value: 0.9856357090076635.
[I 2022-03-27 19:52:20,538] Trial 19 finished with value: 0.9761140473772666 and parameters: {'regressor': 'LightGBM', 'max_depth': 4, 'max_features': 4}. Best is trial 7 with value: 0.9856357090076635.
[I 2022-03-27 19:52:21,183] Trial 20 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:21,859] Trial 21 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:22,519] Trial 22 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:23,274] Trial 23 finished with value: 0.9855384347911574 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 6, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:23,879] Trial 24 finished with value: 0.9851666718949561 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 5}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:24,646] Trial 25 finished with value: 0.9855384347911574 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 6, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:25,221] Trial 26 finished with value: 0.9851666718949561 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 5}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:25,876] Trial 27 finished with value: 0.9845567951821383 and parameters: {'regressor': 'XGBoost', 'max_depth': 6, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:26,047] Trial 28 finished with value: 0.9765224083258769 and parameters: {'regressor': 'LightGBM', 'max_depth': 5, 'max_features': 4}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:26,809] Trial 29 finished with value: 0.9840024346566438 and parameters: {'regressor': 'XGBoost', 'max_depth': 7, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:27,379] Trial 30 finished with value: 0.985691766023269 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 4, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:27,964] Trial 31 finished with value: 0.985691766023269 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 4, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:28,549] Trial 32 finished with value: 0.9851666718949561 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 5}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:29,002] Trial 33 finished with value: 0.9783683994728235 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 3, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:29,656] Trial 34 finished with value: 0.9153488693549434 and parameters: {'regressor': 'RandomForest', 'max_depth': 4, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:30,237] Trial 35 finished with value: 0.9851666718949561 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 5}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:30,806] Trial 36 finished with value: 0.8938298760966701 and parameters: {'regressor': 'RandomForest', 'max_depth': 6, 'max_features': 2}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:31,408] Trial 37 finished with value: 0.985430200504429 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 4, 'max_features': 7}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:31,600] Trial 38 finished with value: 0.9758941121368242 and parameters: {'regressor': 'LightGBM', 'max_depth': 6, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:32,164] Trial 39 finished with value: 0.9842502916631269 and parameters: {'regressor': 'XGBoost', 'max_depth': 5, 'max_features': 7}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:32,747] Trial 40 finished with value: 0.9851482213099071 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 6, 'max_features': 4}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:33,320] Trial 41 finished with value: 0.985691766023269 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 4, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:33,879] Trial 42 finished with value: 0.985691766023269 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 4, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:34,448] Trial 43 finished with value: 0.9851666718949561 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 5}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:34,915] Trial 44 finished with value: 0.9783683994728235 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 3, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:35,645] Trial 45 finished with value: 0.9073338809892725 and parameters: {'regressor': 'RandomForest', 'max_depth': 4, 'max_features': 7}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:36,318] Trial 46 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:36,908] Trial 47 finished with value: 0.9851666718949561 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 5}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:37,651] Trial 48 finished with value: 0.9856357090076635 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 7}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:38,222] Trial 49 finished with value: 0.9842502916631269 and parameters: {'regressor': 'XGBoost', 'max_depth': 5, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:39,098] Trial 50 finished with value: 0.9844596675452194 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 6, 'max_features': 7}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:39,660] Trial 51 finished with value: 0.985691766023269 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 4, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:40,211] Trial 52 finished with value: 0.985691766023269 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 4, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:40,854] Trial 53 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:41,563] Trial 54 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:42,158] Trial 55 finished with value: 0.9851666718949561 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 5}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:42,332] Trial 56 finished with value: 0.9765224083258769 and parameters: {'regressor': 'LightGBM', 'max_depth': 5, 'max_features': 7}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:42,997] Trial 57 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:43,777] Trial 58 finished with value: 0.9634604096785503 and parameters: {'regressor': 'RandomForest', 'max_depth': 6, 'max_features': 5}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:44,280] Trial 59 finished with value: 0.983032001253799 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 6, 'max_features': 3}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:44,921] Trial 60 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:45,597] Trial 61 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:46,273] Trial 62 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:46,910] Trial 63 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:47,555] Trial 64 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:48,279] Trial 65 finished with value: 0.9856357090076635 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 7}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:48,930] Trial 66 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:49,536] Trial 67 finished with value: 0.9851666718949561 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 5}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:49,715] Trial 68 finished with value: 0.9765224083258769 and parameters: {'regressor': 'LightGBM', 'max_depth': 5, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:50,385] Trial 69 finished with value: 0.9845567951821383 and parameters: {'regressor': 'XGBoost', 'max_depth': 6, 'max_features': 5}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:51,137] Trial 70 finished with value: 0.9855384347911574 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 6, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:51,792] Trial 71 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:52,461] Trial 72 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:53,119] Trial 73 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:53,798] Trial 74 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:54,754] Trial 75 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:55,802] Trial 76 finished with value: 0.9856357090076635 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 7}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:56,743] Trial 77 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:57,923] Trial 78 finished with value: 0.9451625573691955 and parameters: {'regressor': 'RandomForest', 'max_depth': 5, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:52:59,097] Trial 79 finished with value: 0.9853949933706203 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 6, 'max_features': 5}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:53:00,226] Trial 80 finished with value: 0.985430200504429 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 4, 'max_features': 7}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:53:01,184] Trial 81 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:53:01,832] Trial 82 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:53:02,481] Trial 83 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:53:02,851] Trial 84 finished with value: 0.9771377197784242 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 2}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:53:03,486] Trial 85 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:53:04,048] Trial 86 finished with value: 0.9842502916631269 and parameters: {'regressor': 'XGBoost', 'max_depth': 5, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:53:04,999] Trial 87 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:53:05,885] Trial 88 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:53:07,156] Trial 89 finished with value: 0.985430200504429 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 4, 'max_features': 7}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:53:07,622] Trial 90 finished with value: 0.9758296442252078 and parameters: {'regressor': 'LightGBM', 'max_depth': 7, 'max_features': 5}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:53:09,254] Trial 91 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:53:10,739] Trial 92 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.
[I 2022-03-27 19:53:12,099] Trial 93 finished with value: 0.9861873336374272 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}. Best is trial 20 with value: 0.9861873336374272.

FrozenTrial(number=20, values=[0.9861873336374272], datetime_start=datetime.datetime(2022, 3, 27, 19, 52, 20, 540546), datetime_complete=datetime.datetime(2022, 3, 27, 19, 52, 21, 183469), params={'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}, distributions={'regressor': CategoricalDistribution(choices=('GradientBoosting', 'XGBoost', 'LightGBM', 'RandomForest')), 'max_depth': IntUniformDistribution(high=7, low=2, step=1), 'max_features': IntUniformDistribution(high=7, low=2, step=1)}, user_attrs={}, system_attrs={}, intermediate_values={}, trial_id=20, state=TrialState.COMPLETE, value=None)

In [46]:
print(study.best_params)

{'regressor': 'GradientBoosting', 'max_depth': 5, 'max_features': 6}

In [47]:
from sklearn.ensemble import GradientBoostingRegressor
from time import time
gbr = GradientBoostingRegressor(random_state=17,max_depth= 6,max_features= 5)
gbr.fit(X_train, y_train)

print('Test Data')
y_pred2 = gbr.predict(X_test)
evalmetric(y_test,y_pred2)

Test Data
MSE: 1692282.8737292925
RMSE: 1300.8777320445195
MAE: 682.6134840169601
MAPE: 5.415860256715757
R-Squared: 0.9836608412393634